### ISSUE TITLE
Calling a function for each retry attempt

### ISSUE THREAD

**Issue by DamianMullins** [coveo/exponential-backoff#15]
Is there any way that we can pass in a function as an option which is called for each retry? 

I'm looking to log retry attempts as they happen, preferably with the attempt number included.

**Comment by samisayegh** [comment]
Yes, the options object accepts a `retry` function that is called after every failed attempt with the error and retry number. It is documented in our [README.md](https://github.com/coveooss/exponential-backoff/blob/master/README.md).

**Comment by DamianMullins** [comment]
Ah, of course, apologies; I really should have read the readme a bit more thoroughly! Thanks for your help!
