### ISSUE TITLE
Feature request: beforeRetry hook

### ISSUE THREAD

**Issue by llirikkk** [coveo/exponential-backoff#18]
It is often useful to be able to perform some actions before each retry, for example, to log that a retry has occurred. 
This can be done by enabling beforeRetry hook, which accepts a function. And before every retry this function is called with the retry number.
Example: https://github.com/sindresorhus/got#hooksbeforeretry

**Comment by samisayegh** [comment]
Hi, a hook is already available. See the [README.md](https://github.com/coveooss/exponential-backoff/blob/master/README.md) for the `retry` function, which receives as arguments the error and the retry number to be attempted.

**Comment by llirikkk** [comment]
I see, thanks. I didn't realize that I could use this function for logging, because README gave me an impression that it could be used only to indicate whether a retry should happen or not. It is like having an affordance, which gives a clue how certain things might be used.
Do you think it makes sense to add a couple of use case examples for this function? Like "this function can also be used to ..."

**Comment by samisayegh** [comment]
I reworked the description of the `retry` function to provide some examples. Feel free to leave any comments,

**Comment by llirikkk** [comment]
Looks good to me, thanks!
