### ISSUE TITLE
Detect attempt limit reached

### ISSUE THREAD

**Issue by CaptainYarb** [coveo/exponential-backoff#29]
The current codebase has a private typescript property `attemptLimitReached`, which happens to work when used by non typescript implementations, but with a more modern TS implementation will make this property private as well.

As a feature being able to detect the limit being reached is fairly essential. Is there any way to expose a getter or method to detect this?

**Comment by samisayegh** [comment]
There are two ways to know that the maximum number of attempts has been reached, depending on the options you have configured.

- If you are using the default `retry` option, it's really easy. Calling `backOff` will return a rejected promise once the limit is hit. If the code path enters your `catch` block, you know that the maximum number of attempts was reached.

- If you are using a custom `retry` function, the most recent attempt number is passed on every invocation (e.g. after the first failed attempt, the `retry` callback will receive `1` as the first argument). By comparing this number with the configured number of attempts, it's possible to set an `attemptLimitReached` flag.

Best,
Sami

**Comment by TiagoGouvea** [comment]
When it exausts the retries, it seems to doesn't return the "internal" error.. I'm right?
How to catch the last error on backOff caller?
