### ISSUE TITLE
Change method signature for usability

### ISSUE THREAD

**Issue by moodysalem** [coveo/exponential-backoff#3]
It's weird that the first argument is not *just* the function when all other arguments are optional

Move retry function to the second argument (backoff options) and make the first argument the function (preferred)

Or make the only argument an object where the only required key is the `fn` key (dislike this because the 'fn' key is not intuitive)

**Comment by samisayegh** [comment]
Sounds good. I'll work on this in the next few days, moving the `retry` to the options.

**Comment by samisayegh** [comment]
Changes made and [published on npm as v2.0.0](https://www.npmjs.com/package/exponential-backoff/v/2.0.0). Thanks for your feedback,
