### ISSUE TITLE
Retry Function based on API Response vs API Error

### ISSUE THREAD

**Issue by NickLiffen** [coveo/exponential-backoff#31]
Hey 👋 

We have a use case where we need to dictate whether to `retry` based on the `response` from an API call, not the `error` from the call. 

I want to perform a retry is `response.data` is equal to an empty object. E.G `{}`. The API won't "error" from this, the response will be a `200` and it has got some data back, the data is just an empty object. 

Right now, the `retry` function only allows you to access the `error` and the number of attempts. In my use case that doesn't quite seem to fit the need 😢 

Maybe I am missing something in your docs (and I'm sorry if I am), I have done some trial and error locally on my machine, but I can't seem to access the `response` in the `retry` function. 

Have you got an example of this working, if not, is it something you would think about incorporating?

**Comment by NickLiffen** [comment]
E.G when you state `The retry function can be used to run logic after every failed attempt`. I need to define "failed attempt" as to where the `response.data` from the API query is an empty object.

**Comment by samisayegh** [comment]
Hi Nick,

The `backOff` utility and `retry` option are intentionally abstract to be able to back off any JavaScript function. The passed function may be performing a http request as in your case, or communicating with a database, or accessing a file from the filesystem etc.

> I need to define "failed attempt"

Exactly, since the http call does not throw, you would need to throw when you detect a failed attempt so that `backOff` knows to reattempt the call. e.g.

```
const request = () => {
    const response = // perform http call
    const {data} = response;
    const hasData = Object.keys(data).length !== 0;
    
    if (!hasData) {
        throw ...
    }

    return data;
}

backOff(request)
```

**Comment by NickLiffen** [comment]
Thanks @samisayegh 👍  you are 100% right and I got this working by throwing my own error on my own terms from the function that gets the data 👍 It is working as expected. I appreciate your response though! 💯 I am going to close this issue as this is not an issue with the library 👍
