### ISSUE TITLE
Add Copyright to License

### ISSUE THREAD

**Issue by VaeterchenFrost** [coveo/exponential-backoff#39]
Hello,

the License attached to the project does ot contain any information about the copyright holder(s).
See the last paragraph of the https://github.com/coveooss/exponential-backoff/blob/master/LICENSE

This would help in attributing the module in case it is reused under the license.

Thanks in advance!

**Comment by samisayegh** [comment]
Hello Martin,

Indeed the license is being applied incompletely. I'll see what I can do,
