### ISSUE TITLE
IBackOffOptions aren't optional

### ISSUE THREAD

**Issue by uythoang** [coveo/exponential-backoff#51]
None of the properties of [IBackOffOptions](https://github.com/coveooss/exponential-backoff/blob/master/src/options.ts) are optional, even though the Readme states that they all are:

```
export interface IBackOffOptions {
  delayFirstAttempt: boolean;
  jitter: JitterType;
  maxDelay: number;
  numOfAttempts: number;
  retry: (e: any, attemptNumber: number) => boolean | Promise<boolean>;
  startingDelay: number;
  timeMultiple: number;
}
```

**Comment by samisayegh** [comment]
That's correct, the [code](https://github.com/coveooss/exponential-backoff/blob/master/src/backoff.ts#L8) actually takes `Partial<IBackoffOptions>`. Will adjust to reflect this,
