### ISSUE TITLE
Inverse exponential backoff

### ISSUE THREAD

**Issue by davepaiva** [coveo/exponential-backoff#54]
Is there any scope for adding functionality for inverse exponential backoff?
A simple DX would be to add a negative integer value to the `timeMultiple` , a `minDelay` optioion.

There are multiple uses case especially when we use polling APIs to get the result of an async task.
It doesn't make sense increase the wait time exponentially if the task has been finished before the next polling cycle.

**Comment by samisayegh** [comment]
Hi Dave, would the `timeMultiple` be a fraction in this case?

e.g. with timeMultiple: `0.5`, startingDelay: `10s`, retries: `3`
delays would be: `10s` -> `5s` -> `2.5s`

If so, maybe the behavior can already be achieved with the current options? Could you share example values for your use-case?

**Comment by davepaiva** [comment]
> Hi Dave, would the `timeMultiple` be a fraction in this case?
> 
> e.g. with timeMultiple: `0.5`, startingDelay: `10s`, retries: `3` delays would be: `10s` -> `5s` -> `2.5s`
> 
> If so, maybe the behavior can already be achieved with the current options? Could you share example values for your use-case?

makes sense, using fractions solved the issue
